[package]
name = "cobra"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
sha1 = "0.10.6"
flate2 = "1.0.28"
byteorder = "1.5.0"
hex = "0.4.3"
walkdir = "2.4.0"

[dev-dependencies]
tempfile = "3.8.1"
